config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => '/cable'

  root 'chatrooms#index'

  resources :messages

  resources :users, only:[:new, :create] do
    resources :chatrooms, only: [:index, :show, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  validates :identifier, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :chatrooms, through: :subscriptions

  def existing_chats_users
    existing_chat_users = []
    chatrooms.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: id).map { |subscription| subscription.user })
    end
    existing_chat_users.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
require 'securerandom'

class ChatroomsController < ApplicationController
  def index
    if current_user.present?
      @chats = current_user.chatrooms
      @existing_chats_users = current_user.existing_chats_users
    end
    @users = User.all
  end

  def show
    @chat = Chatroom.find(params[:id])
    @message = Message.new
    @other_user = User.find(params[:other_user])
  end


  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chatroom.new(identifier: SecureRandom.hex)
    unless @chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chatroom_path(current_user, @chat, other_user: @other_user.id)
  end

  private

  def find_chat(second_user)
    chats = current_user.chatrooms
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    nil
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  protect_from_forgery with: :null_session, only: :destroy

  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast "messages_#{message_params[:chat_id]}",
                                   message: message.content,
                                   user: message.user.username,
                                   user_email: message.user.email,
                                   created_at: message.created_at.strftime("%H:%M"),
                                   url: url_for(action: :show, id: message)
      head :ok
    else
      redirect_to root_path
    end
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    head :no_content
  end

  private

  def message_params
    params.require(:message).permit(:content, :chatroom_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/index.html.erb
<% if current_user.present? %>
  <div class="row">
    <p class="mt-2">You - <b><%= current_user.email %></b></p>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-danger ml-5' %>
  </div>
<% else %>
  <%= link_to 'Log in', new_user_session_path, class: 'btn btn-success' %>
  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success' %>
<% end %>

<h1 class="text-center mt-5">Your Dialogs</h1>
<% if @existing_chats_users.present? %>
  <% @existing_chats_users.each do |other_user| %>
    <% unless other_user == current_user %>
      <%= link_to(user_chatrooms_path(current_user, other_user: other_user.id), method: :post) do %>
        <%= other_user.email %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<h1 class="text-center mt-5">All Users</h1>
<% if current_user.present? %>
  <% @users.each do |other_user| %>
    <% unless other_user == current_user %>
      <%= link_to(user_chatrooms_path(current_user, other_user: other_user.id), method: :post) do %>
        <%= other_user.email %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/chatrooms/show.html.erb
<div>
  <h2 class="text-center">Chat with <%= @other_user.email %></h2>

  <div class="panel panel-default dialog-window mb-4">
    <% if @chat.messages.exists? %>
      <div class="panel-body" id="messages">
        <%= render @chat.messages %>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>

  <%= render partial: 'messages/message_form' %>
</div>

<!--<script>-->
<!--  createMessageChannel();-->
<!--</script>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableMessenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/65f453e416.js"></script>
  </head>

  <body class="container mt-5">
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="row mb-4 ml-3 mt-4">
  <div class="col-10">
    <p><b><%= message.user.email %></b> </p>
    <p><%= message.content %></p>
  </div>

  <span class="ml-4"><%= message.created_at.strftime("%H:%M") %></span>
  <%= link_to message_path(message), method: :delete, class: 'delete ml-5' do %>
    <i class="fas fa-times"></i>
  <% end %>
</div>

app/views/messages/_message_form.html.erb
<%= form_for @message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :content, 'Enter your message:' %>
  <%= f.text_field :content, class: "form-control input" %>
  <br>
  <%= f.hidden_field :chatroom_id, value: @chat.id %>
  <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
  <%= f.submit "Send", class: "btn btn-primary float-right" %>
<% end %>